"""add knowledge base permissions

Revision ID: 5a1e14f44505
Revises: 41f2d674d60f
Create Date: 2026-09-03 23:13:50.431703
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '5a1e14f44505'
down_revision: str | None = '41f2d674d60f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='permission_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_base_id', 'user_id', name='uq_knowledge_base_permission')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_base_permissions')
    # ### end Alembic commands ###
    # Alembic не удаляет ENUM-типы автоматически: без этого повторный
    # upgrade падает с DuplicateObject.
    sa.Enum(name='permission_role').drop(op.get_bind(), checkfirst=True)
